// ESB64 fuzz entry: differential fuzz vs Node's native atob/btoa, Buffer and
// TextDecoder. Deterministic (seedable via ESB64_FUZZ_ARGS provisioned by
// tests/fuzz.mjs). Failures throw at the end (nonzero exit via the harness).
import {
  btoa as esb64Btoa,
  atob as esb64Atob,
  encodeUtf8,
  decodeUtf8,
  utf8Encode
} from '../src/index';

var iterations: number = parseInt(ESB64_FUZZ_ARGS[0] || '5000', 10);
var seed: number = parseInt(ESB64_FUZZ_ARGS[1] || '42', 10);

var state = seed >>> 0;
function rnd(): number {
  state = (state * 1664525 + 1013904223) >>> 0;
  return state / 4294967296;
}
function rndInt(max: number): number {
  return Math.floor(rnd() * max);
}

function latin1String(len: number): string {
  var s = '';
  for (var i = 0; i < len; i++) s += String.fromCharCode(rndInt(256));
  return s;
}

function asciiString(len: number): string {
  var alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/= \t\n\f\r';
  var s = '';
  for (var i = 0; i < len; i++) s += alpha.charAt(rndInt(alpha.length));
  return s;
}

function unicodeString(len: number): string {
  var ranges = [[0x20, 0x7e], [0x80, 0x7ff], [0x800, 0xd7ff], [0xe000, 0xffff], [0x10000, 0x10ffff]];
  var s = '';
  for (var i = 0; i < len; i++) {
    var r = ranges[rndInt(ranges.length)];
    var cp = r[0] + rndInt(r[1] - r[0] + 1);
    if (cp >= 0x10000) {
      var c = cp - 0x10000;
      s += String.fromCharCode(0xd800 + (c >> 10), 0xdc00 + (c & 0x3ff));
    } else {
      s += String.fromCharCode(cp);
    }
  }
  return s;
}

// Strings that deliberately contain LONE surrogates (the encoder's trickiest
// branch - TextEncoder replaces them with U+FFFD, encodeURIComponent throws).
function loneSurrogateString(len: number): string {
  var pieces = ['\ud800', '\udbff', '\udc00', '\udfff', '\ud800a', 'b\udc00', '\ud83d\ude00', '\ud800\ud83d\ude00', 'x'];
  var s = '';
  for (var i = 0; i < len; i++) {
    s += pieces[rndInt(pieces.length)];
  }
  return s;
}

function encodeOrThrow(fn: () => any): any {
  try {
    return fn();
  } catch (e: any) {
    // Compare error NAMES too (InvalidCharacterError vs URIError etc.):
    // 'THREW:<name>' diverges when the two sides throw different error types.
    return 'THREW:' + (e && e.name ? e.name : 'unknown');
  }
}

var divergences = 0;
var checks = 0;

function check(name: string, ours: any, native: any): void {
  checks++;
  if (ours !== native) {
    divergences++;
    if (divergences <= 20) console.error('  DIV ' + name + ': ours=' + JSON.stringify(String(ours).slice(0, 80)) + ' native=' + JSON.stringify(String(native).slice(0, 80)));
  }
}

// 1. btoa parity: random latin1 strings.
for (var i = 0; i < iterations; i++) {
  var s = latin1String(rndInt(300));
  check('btoa latin1', encodeOrThrow(function (): any { return esb64Btoa(s); }), encodeOrThrow(function (): any { return btoa(s); }));
}

// 2. btoa parity: arbitrary unicode strings - both must throw
//    InvalidCharacterError (compared as 'THREW').
for (var j = 0; j < iterations; j++) {
  var u = unicodeString(rndInt(40));
  check('btoa unicode both-throw', encodeOrThrow(function (): any { return esb64Btoa(u); }), encodeOrThrow(function (): any { return btoa(u); }));
}

// 3. atob parity: random ASCII-ish b64 text (alphabet + whitespace + '=').
for (var k = 0; k < iterations; k++) {
  var b = asciiString(rndInt(200));
  check('atob ascii', encodeOrThrow(function (): any { return esb64Atob(b); }), encodeOrThrow(function (): any { return atob(b); }));
}

// 4. atob parity: random bytes encoded with native btoa, then random mutation.
for (var m = 0; m < iterations; m++) {
  var raw = latin1String(rndInt(100));
  var good = btoa(raw);
  var mut = good.split('');
  var nMut = rndInt(4);
  var alpha = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=!';
  for (var mm = 0; mm < nMut && mut.length > 0; mm++) {
    mut[rndInt(mut.length)] = alpha.charAt(rndInt(alpha.length));
  }
  var mutated = mut.join('');
  check('atob mutated', encodeOrThrow(function (): any { return esb64Atob(mutated); }), encodeOrThrow(function (): any { return atob(mutated); }));
}

// 5. encodeUtf8 parity vs Buffer.
for (var e5 = 0; e5 < iterations; e5++) {
  var us = unicodeString(rndInt(60));
  check('encodeUtf8 buffer parity', encodeOrThrow(function (): any { return encodeUtf8(us); }), encodeOrThrow(function (): any { return Buffer.from(us, 'utf8').toString('base64'); }));
}

// 6. decodeUtf8 round trip (valid byte streams generated by encode).
for (var r = 0; r < iterations; r++) {
  var rs = unicodeString(rndInt(60));
  check('decodeUtf8 roundtrip', encodeOrThrow(function (): any { return decodeUtf8(encodeUtf8(rs)); }), rs);
}

// 7. decodeUtf8 parity vs TextDecoder on VALID byte streams only. Node's
//    TextDecoder is ICU-backed and diverges from the WHATWG error grouping on
//    malformed sequences (ICU emits one FFFD per bad byte); malformed-input
//    expectations are hardcoded vectors, not oracle-differenced.
//    ignoreBOM: true - TextDecoder strips a leading U+FEFF by default, but
//    the codec must round-trip BOMs byte-exactly (it's data, not a stream).
for (var t = 0; t < iterations; t++) {
  var bytes = utf8Encode(unicodeString(rndInt(60)));
  var b64 = btoa(bytes);
  check('decodeUtf8 TextDecoder parity', encodeOrThrow(function (): any { return decodeUtf8(b64); }),
    encodeOrThrow(function (): any { return new TextDecoder('utf-8', { ignoreBOM: true }).decode(Buffer.from(bytes, 'binary')); }));
}

// 8. Lone surrogates: btoa must throw InvalidCharacterError on both sides
//    (with matching error NAMES), encodeUtf8 must match Buffer's U+FFFD
//    replacement, and the decode round-trip must yield the normalized text.
for (var l = 0; l < iterations; l++) {
  var ls = loneSurrogateString(rndInt(20) + 1);
  check('btoa lone-surrogate both-throw', encodeOrThrow(function (): any { return esb64Btoa(ls); }),
    encodeOrThrow(function (): any { return btoa(ls); }));
  check('encodeUtf8 lone-surrogate buffer parity', encodeOrThrow(function (): any { return encodeUtf8(ls); }),
    encodeOrThrow(function (): any { return Buffer.from(ls, 'utf8').toString('base64'); }));
  check('decodeUtf8 lone-surrogate roundtrip', encodeOrThrow(function (): any { return decodeUtf8(encodeUtf8(ls)); }),
    encodeOrThrow(function (): any { return Buffer.from(ls, 'utf8').toString('utf8'); }));
}

// 9. NULs and control chars through the utf8 lanes (the unicodeString
//    generator never emits them).
for (var n9 = 0; n9 < iterations; n9++) {
  var ctrl = '';
  var cn = rndInt(40);
  for (var ci = 0; ci < cn; ci++) {
    var code = rndInt(64); // 0x00-0x3F covers NUL + C0 controls + ASCII
    ctrl += String.fromCharCode(code);
  }
  check('encodeUtf8 control-chars parity', encodeOrThrow(function (): any { return encodeUtf8(ctrl); }),
    encodeOrThrow(function (): any { return Buffer.from(ctrl, 'utf8').toString('base64'); }));
  check('decodeUtf8 control-chars roundtrip', encodeOrThrow(function (): any { return decodeUtf8(encodeUtf8(ctrl)); }), ctrl);
}

console.log('ESB64 fuzz: ' + checks + ' checks, ' + divergences + ' divergence(s), seed ' + seed);
if (divergences > 0) {
  throw new Error(divergences + ' divergence(s)');
}
