// WPT base64 corpus: verbatim transcription of
// web-platform-tests/fetch/data-urls/resources/base64.json (fetched
// 2026-08-06), the corpus the WPT atob() tests run against in browsers.
// Each entry: [input, expectedBytes] where expectedBytes is the decoded byte
// array, or null when the input MUST throw InvalidCharacterError (forgiving
// base64 decode failure).
export type WptEntry = [string, number[] | null];

export var WPT_B64_CORPUS: WptEntry[] = [
  ['', []],
  ['abcd', [105, 183, 29]],
  [' abcd', [105, 183, 29]],
  ['abcd ', [105, 183, 29]],
  [' abcd===', null],
  ['abcd=== ', null],
  ['abcd ===', null],
  ['a', null],
  ['ab', [105]],
  ['abc', [105, 183]],
  ['abcde', null],
  ['\ud800\udc00', null],
  ['=', null],
  ['==', null],
  ['===', null],
  ['====', null],
  ['=====', null],
  ['a=', null],
  ['a==', null],
  ['a===', null],
  ['a====', null],
  ['a=====', null],
  ['ab=', null],
  ['ab==', [105]],
  ['ab===', null],
  ['ab====', null],
  ['ab=====', null],
  ['abc=', [105, 183]],
  ['abc==', null],
  ['abc===', null],
  ['abc====', null],
  ['abc=====', null],
  ['abcd=', null],
  ['abcd==', null],
  ['abcd===', null],
  ['abcd====', null],
  ['abcd=====', null],
  ['abcde=', null],
  ['abcde==', null],
  ['abcde===', null],
  ['abcde====', null],
  ['abcde=====', null],
  ['=a', null],
  ['=a=', null],
  ['a=b', null],
  ['a=b=', null],
  ['ab=c', null],
  ['ab=c=', null],
  ['abc=d', null],
  ['abc=d=', null],
  ['ab\u000Bcd', null],
  ['ab\u3000cd', null],
  ['ab\u3001cd', null],
  ['ab\tcd', [105, 183, 29]],
  ['ab\ncd', [105, 183, 29]],
  ['ab\fcd', [105, 183, 29]],
  ['ab\rcd', [105, 183, 29]],
  ['ab cd', [105, 183, 29]],
  ['ab\u00a0cd', null],
  ['ab\t\n\f\r cd', [105, 183, 29]],
  [' \t\n\f\r ab\t\n\f\r cd\t\n\f\r ', [105, 183, 29]],
  ['ab\t\n\f\r =\t\n\f\r =\t\n\f\r ', [105]],
  ['A', null],
  ['/A', [252]],
  ['//A', [255, 240]],
  ['///A', [255, 255, 192]],
  ['////A', null],
  ['/', null],
  ['A/', [3]],
  ['AA/', [0, 15]],
  ['AAAA/', null],
  ['AAA/', [0, 0, 63]],
  ['\u0000nonsense', null],
  ['abcd\u0000nonsense', null],
  ['YQ', [97]],
  ['YR', [97]],
  ['~~', null],
  ['..', null],
  ['--', null],
  ['__', null]
];
